openapi: 3.0.3
info:
  title: MebloPlan Scanner API
  version: 0.1.0
paths:
  /api/scans:
    post:
      summary: Upload scan data and convert to GLB.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: ZIP file containing scan data.
                meta:
                  type: string
                  description: Additional metadata encoded as JSON or URL-encoded string.
      responses:
        '200':
          description: Conversion completed.
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
        '500':
          description: Server error.
  /api/scans/{id}/room.glb:
    get:
      summary: Download converted GLB model by scan id.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: GLB file.
          content:
            model/gltf-binary:
              schema:
                type: string
                format: binary
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
        '404':
          description: Not found.
        '500':
          description: Server error.
