openapi: 3.0.3
info:
  title: MebloPlan Scanner API
  version: 0.1.0
paths:
  /health:
    get:
      summary: Service health check.
      responses:
        '200':
          description: Service is up.
  /api/scans:
    get:
      summary: List stored scan identifiers.
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          description: 1-based page number.
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Maximum items per page.
          schema:
            type: integer
            minimum: 1
            default: 100
      responses:
        '200':
          description: Array of scan identifiers.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: uuid
        '401':
          description: Unauthorized.
        '429':
          description: Too many requests.
        '500':
          description: Server error.
    post:
      summary: Upload scan data and convert to GLB.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: OBJ, PLY, USD/USDA/USDZ
                meta:
                  type: string
                  description: Additional metadata encoded as JSON or URL-encoded string.
      responses:
        '200':
          description: Conversion completed.
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - url
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Unique scan ID.
                  url:
                    type: string
                    format: uri
                    description: Full URL to download the GLB file.
                    example: http://localhost:4000/api/scans/123e4567-e89b-12d3-a456-426614174000/room.glb
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
        '429':
          description: Too many requests. Conversion queue is full.
        '500':
          description: Server error.
  /api/scans/{id}:
    get:
      summary: Retrieve conversion status by id.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: Unique scan ID.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Conversion status information.
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                  - progress
                properties:
                  status:
                    type: string
                    description: Current conversion state.
                  progress:
                    type: integer
                    minimum: 0
                    maximum: 100
                    description: Conversion progress percentage.
                  url:
                    type: string
                    format: uri
                    description: Download URL when conversion finished.
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
        '404':
          description: Not found.
        '429':
          description: Too many requests.
        '500':
          description: Server error.
    delete:
      summary: Delete scan directory by id.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: Unique scan ID.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Scan deleted.
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
        '404':
          description: Not found.
        '429':
          description: Too many requests.
        '500':
          description: Server error.
  /api/scans/{id}/info:
    get:
      summary: Retrieve scan metadata by scan id.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: Unique scan ID.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Metadata saved during upload.
          headers:
            Cache-Control:
              description: Cache policy for the metadata.
              schema:
                type: string
              example: public, max-age=86400, immutable
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
        '404':
          description: Not found.
        '429':
          description: Too many requests.
        '500':
          description: Server error.
    head:
      summary: Check scan metadata existence by scan id.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: Unique scan ID.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Metadata exists.
          headers:
            Cache-Control:
              description: Cache policy for the metadata.
              schema:
                type: string
              example: public, max-age=86400, immutable
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
        '404':
          description: Not found.
        '429':
          description: Too many requests.
        '500':
          description: Server error.
  /api/scans/{id}/room.glb:
    get:
      summary: Download converted GLB model by scan id.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: Unique scan ID.
          required: true
          schema:
            type: string
            format: uuid
        - name: If-None-Match
          in: header
          description: ETag previously returned for the model.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: GLB file.
          headers:
            Cache-Control:
              description: Cache policy for the model.
              schema:
                type: string
              example: public, max-age=86400, immutable
            ETag:
              description: Entity tag for the model. Constant for a given file.
              schema:
                type: string
            Content-Disposition:
              description: Suggested filename for download. Uses `filename` from info.json if present.
              schema:
                type: string
              example: attachment; filename="room.glb"
            Content-Length:
              description: Size of the model in bytes.
              schema:
                type: integer
        content:
          model/gltf-binary:
            schema:
              type: string
              format: binary
        '304':
          description: Not modified.
          headers:
            ETag:
              description: Entity tag for the model. Constant for a given file.
              schema:
                type: string
            Content-Length:
              description: Size of the model in bytes.
              schema:
                type: integer
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
        '404':
          description: Not found.
        '429':
          description: Too many requests.
        '500':
          description: Server error.
    head:
      summary: Check converted GLB model by scan id.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: Unique scan ID.
          required: true
          schema:
            type: string
            format: uuid
        - name: If-None-Match
          in: header
          description: ETag previously returned for the model.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: GLB file headers.
          headers:
            Cache-Control:
              description: Cache policy for the model.
              schema:
                type: string
              example: public, max-age=86400, immutable
            ETag:
              description: Entity tag for the model. Constant for a given file.
              schema:
                type: string
            Content-Disposition:
              description: Suggested filename for download. Uses `filename` from info.json if present.
              schema:
                type: string
              example: attachment; filename="room.glb"
            Content-Length:
              description: Size of the model in bytes.
              schema:
                type: integer
        '304':
          description: Not modified.
          headers:
            ETag:
              description: Entity tag for the model. Constant for a given file.
              schema:
                type: string
            Content-Length:
              description: Size of the model in bytes.
              schema:
                type: integer
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
        '404':
          description: Not found.
        '429':
          description: Too many requests.
        '500':
          description: Server error.
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
