name: CI iOS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ios:
    if: ${{ hashFiles('apps/ios/*.xcodeproj', 'apps/ios/*.xcworkspace') != '' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Install dependencies
        working-directory: apps/ios
        run: |
          if [ -f "Podfile" ]; then
            sudo gem install cocoapods
            pod install
          fi
      - name: Build and test
        working-directory: apps/ios
        run: |
          xcodebuild -scheme MebloPlanScannerApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' build test
